name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Build
      run: |
        gem install bundler
        bundle -v
        rm Gemfile.lock || true
        gem update --system $RUBYGEMS_VERSION
        gem --version
        bundle -v
        bundle install --without system_tests --path vendor/bundle --jobs 4 --retry 3
    - name: Validate
      env:
        PUPPET_GEM_VERSION: '~> 6'
      run: |
        bundle exec rake syntax lint metadata_lint check:symlinks check:git_ignore check:dot_underscore check:test_file rubocop
    - name: Tests
      env:
        PUPPET_GEM_VERSION: '~> 6'
      run: |
        bundle exec rake parallel_spec
